### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by EricMaibach** [yorek/debezium-sql-change-stream#4]
The Debezium API is not secured by default, anyone can access it.  And the API call gives full configuration information about the connector, including the database username and password in plain text.  The script for putting this in Azure creates a container with a public IP address.  So this tutorial creates a Azure service that makes the database password publicly available on the internet.

This tutorial should be changed to give warnings about the security dangers of deploying Debezium to Azure, and show how to implement this correctly (at a very minimum store the password in a configuration file and setup firewall rules for the container to limit who can access it),

**Comment by yorek** [comment]
Hey Eric. You are absolutely right. This example favored simplicity over security, as it just aims to provide a starting point, not a complete, production-ready, deployable, solution. Would be great if you can contribute and make the changes you think are needed to make the repo better.
