### ISSUE TITLE
Update instructions to run the demo with Debezium 2.7

### ISSUE THREAD

**Issue by AlessandroLollo** [yorek/debezium-sql-change-stream#8]
Hey there 👋 

In the last few weeks I've spent some time getting Debezium 2.7 working with Azure SQL and Azure Event Hub.
This repo has been a great starting point!

However, I had to made some changes to get the Debezium SQL Server connector to work properly with Debezium 2.7, mainly due to some changes that have been introduces since Debezium 2.0.

I'd be keen to contribute to this repo to provide instructions on how to setup Azure SQL with Debezium 2.7 and Azure Event Hub.
Let me know what you think!

Best,
Ale

**Comment by yorek** [comment]
Absolutely! Please fork the repo, update the instructions and submit a PR so that I can review and merge it. Thanks!

**Comment by AlessandroLollo** [comment]
Great! Thanks @yorek, will do!

**Comment by AlessandroLollo** [comment]
Hey @yorek 👋 

Here's the PR --> https://github.com/Azure-Samples/azure-sql-db-change-stream-debezium/pull/9
Still draft, but feel free to take a look if you want!
Feedbacks are welcome 😊

**Comment by yorek** [comment]
Closing as fixed by #9. Thanks a lot!
